### ISSUE TITLE
It still shows Suspense fallback 

### ISSUE THREAD

**Issue by user753** [theKashey/react-prerendered-component#7]
I use it with react-span
```jsx
const prefetchMap = new WeakMap();
const prefetchLazy = LazyComponent => {
  if (!prefetchMap.has(LazyComponent)) {
    prefetchMap.set(LazyComponent, LazyComponent._ctor());
  }
  return prefetchMap.get(LazyComponent);
};

const prerenderedLazy = dynamicImport => {
  const LazyComponent = React.lazy(dynamicImport);
  return React.memo(props => (
    <PrerenderedComponent live={prefetchLazy(LazyComponent)}>
      <LazyComponent {...props} />
    </PrerenderedComponent>
  ));
};

const MyComponent = prerenderedLazy(() => import("./MyComponent"));


const App =  <Router>
      <React.Suspense fallback={<Spinner/>}>
        <Switch>         
          <Route path={'/foo'} exact component={MyComponent} />
         </Switch> 
       </React.Suspense>
    </Router>

const rootElement = document.getElementById("root")
if (rootElement.hasChildNodes()) {
  ReactDOM.hydrate(<App />, rootElement);
} else {
  ReactDOM.render(<App />, rootElement);
}

```
After build and react-snap when I open /foo browser show the prerendered page then Spinner and then the page again.

**Comment by theKashey** [comment]
Working for me.
Keep in mind - IDs of components should be equal between client and the server.

https://codesandbox.io/s/mutable-dawn-qy7od

**Comment by user753** [comment]
> Working for me.

What do you mean?
It shows 
`"pre-rendered" lazy stuff`
then it shows
`loading...`
then it shows 
`lazy stuff`
I thought the idea of `PrerenderedComponent` that it doesn't show Suspense fallback 
I changed the example. 
https://codesandbox.io/s/blissful-antonelli-mg35y
Now prerender is the same as lazy `foobar`. Is it possible to not show `loading...`?

**Comment by user753** [comment]
@theKashey any thoughts?

**Comment by theKashey** [comment]
With the real "import" it would work out of the box.

https://codesandbox.io/s/wispy-surf-lrm6h - am "remembering" resolved value, like `webpack` would remember resolved module inside module cache, so I am not "importing" stuff twice, and not executing `setTimeout` twice.
You don't have to do it by yourself - just `import`, here is another example - https://codesandbox.io/s/beautiful-kapitsa-lol99 - I've moved `child` to a separate file, and that's all.
