### ISSUE TITLE
Flash of white screen with preact

### ISSUE THREAD

**Issue by iMakedonsky** [theKashey/react-prerendered-component#8]
Lib is very nice in preventing a flash of white page with React & react-snap.

I know it's kind of not an issue with this library directly, but there is still a flash when using preact 10.5.13 via `preact/compat` webpack alias.

**Comment by theKashey** [comment]
preact does not have real VDOM which might be required for this trick, and I am not very sure what is the best approach to address this issue.

Try another one, a non documented, but actually working pretty great (and actually doing a partial hydration). It's just two lines of code
```js
        suppressHydrationWarning   
        dangerouslySetInnerHTML={{ __html: "" }}
```
Example - https://github.com/hadeeb/react-lazy-hydration/blob/master/src/index.tsx#L161

**Comment by marvinhagemeister** [comment]
> preact does not have real VDOM

Let us please be more respective towards other open source projects one is not knowledgeable in. One way to do that is to do a quick google search to back up opinions before stating them as facts. Otherwise that sentence you wrote comes of as pretty rude.

With "real VDOM" I'm assuming that you're referring to the 2016-2018 era of Preact where we compared the VDOM tree directly with the DOM. This is not the case anymore since two years. We compare two VDOM trees internally like React does.

**Comment by theKashey** [comment]
@marvinhagemeister - with no disrespect I have no problems using solutions with or without VDOM, in the meantime collaborating in one closed-source no-VDOM solution.

However, I should confirm that the fact that Preact(X?) is now backed by VDOM abstraction, still being ultra-compact, was unknown to me. And I would like to read some reasoning for that. Maybe I should go VDOM by myself?

----

In any case, lets try to make peace, not war. The initial question was about partial hydration for preact, and the only known example of "preact doing it"(well, @developit doing it) is actually react - https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/master/react-progressive-hydration/app/components/hydrator.js#L37

I've tried to [google something](https://www.google.com/search?q=preact+partial+hydration), but was not able to find _real_ any answer.

**Comment by marvinhagemeister** [comment]
We don't advertise that we switched to VDOM <-> VDOM diffing much as it's an implementation detail and most users care more about higher level detail. So there is no marketing material available for that aspect. Peeking at Preact's source [makes that obvious though](https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/diff/index.js#L25-L35).

For partial/progressive hydration the current best option for Preact applications is [`preact-iso`](https://www.npmjs.com/package/preact-iso) which is the current recommended way. The future Preact v11 will make that even easier through new primitives. We had partial hydration working on https://preactjs.com/ which is probably the oldest attempt at that.

> I've tried to google something, but was not able to find real any answer.

It's true that we need to invest more into our marketing and SEO. We've been getting more instances where people jumped to conclusion based on missing marketing pages or not matching the exact keywords they were looking for. That's something we need to improve on.

**Comment by theKashey** [comment]
So look like we have an answer:
- `prerendered-component` is a little old-school solution and actually cannot do partial hydration even for React. It does the full hydration, just letting the JS code be used a little later. Later, on the "replacement" you will get a "Flash of on cached images", as the old DOM tree will be destroyed, and the new created.
- `dangerouslySetInnerHTML={{ __html: "" }}` is actually doing partial hydration, but only "one level down", and only for React.
- __the only recommended solution__ for preact is to use `preact-iso`, where this moment is a part of a router functionality.

There is no concrete answer how to use it for something smaller than a page (menu, footer and so on), however, any further discussions should be made in a proper place -> https://github.com/preactjs/wmr/tree/main/packages/preact-iso

@marvinhagemeister - thanks for providing the all required information.

**Comment by iMakedonsky** [comment]
Issue is resolved with `preact-iso`. Thanks a lot you both for taking part in that!
